#!/usr/bin/env python3
"""
One-time migration: split public/events.json into data/events/active.json
and data/events/archive.json based on whether events are past or future.

Also seeds data/events/pending.json as empty.

Run: python3 scripts/migrate_to_event_store.py
"""

import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
import atomic_io  # noqa: E402

EVENTS_JSON = ROOT / "public" / "events.json"
EVENTS_DIR = ROOT / "data" / "events"
ACTIVE_JSON = EVENTS_DIR / "active.json"
ARCHIVE_JSON = EVENTS_DIR / "archive.json"
PENDING_JSON = EVENTS_DIR / "pending.json"

EVENTS_DIR.mkdir(parents=True, exist_ok=True)


def parse_date(iso_str: str) -> datetime | None:
    try:
        dt = datetime.fromisoformat(iso_str)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except (ValueError, TypeError):
        return None


def main():
    if not EVENTS_JSON.exists():
        print(f"ERROR: {EVENTS_JSON} not found")
        sys.exit(1)

    events = atomic_io.read_json(EVENTS_JSON, default=[])
    print(f"Loaded {len(events)} events from {EVENTS_JSON}")

    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=24)

    active = []
    archive = []

    for ev in events:
        # For recurring events, check last recurrence date
        last_date_str = ev.get("startDate", "")
        if ev.get("recurrences"):
            last_date_str = ev["recurrences"][-1]

        dt = parse_date(last_date_str)

        if dt and dt < cutoff:
            ev["archivedAt"] = now.isoformat()
            archive.append(ev)
        else:
            # Add source field back (needed for internal tracking)
            if "source" not in ev:
                ev["source"] = ""
            active.append(ev)

    print(f"\nSplit results:")
    print(f"  Active (future/current): {len(active)} events")
    print(f"  Archive (past):          {len(archive)} events")

    atomic_io.write_json(ACTIVE_JSON, active)
    print(f"\nWrote {ACTIVE_JSON}")

    atomic_io.write_json(ARCHIVE_JSON, archive)
    print(f"Wrote {ARCHIVE_JSON}")

    if not PENDING_JSON.exists():
        atomic_io.write_json(PENDING_JSON, [])
        print(f"Created empty {PENDING_JSON}")

    print("\nMigration complete!")
    print("The event store is now ready. Use MCP tools to manage events.")
    print("  - public/events.json is now a build artifact (regenerated by event_publish)")
    print("  - data/events/active.json is the source of truth for live events")
    print("  - data/venues.json holds permanent weekly venues (was public/recurring.json)")


if __name__ == "__main__":
    main()
